name: Deploy website to S3

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}  # lets you trigger manually from the Actions tab too

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # required for OIDC
      contents: read    # required to checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Later, if you want CI to run your Python generator, you'll add setup-python + run script here.

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::134705967758:role/github-actions-cloudtopher-deploy
          aws-region: us-east-1   # or your actual region


      - name: Sync files to S3
        run: |
          aws s3 sync . "s3://${{ vars.S3_BUCKET }}" \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ vars.CF_DISTRIBUTION_ID }}" \
            --paths "/*"
